name: Build

on:
  workflow_dispatch:
    inputs:
        version:
          description: 'VERSION'
          required: true
          default: 'latest'

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2

    - name: Build
      run: |
          docker build -t . "test-one:${VERSION}"
          docker save "test-one:${VERSION}" | gzip > /tmp/test-one.${VERSION}.tar.gz
          echo curl -d @/tmp/test-one.${VERSION}.tar.gz -H "Authorization: ${ROQ_TOKEN}" http://roq.tech/deploy
      env:
        ROQ_TOKEN: ${{ secrets.ROQ_TOKEN }}
        VERSION: ${{ github.event.inputs.version }}
